### ISSUE TITLE
Builtin browser opens while disabled in settings

### ISSUE THREAD

**Issue by Shaloum** [Kvan7/Exiled-Exchange-2#103]
### Description
Pressing 'Browser' opens builtin browser even with it disabled.

### Reproduction steps
Price check an item with resistance 'pseudo' mod;
Press 'Browser' button in error message.

<details>
<summary>Item example</summary>
Item Class: Helmets
Rarity: Rare
Rage Brow
Expert Cowled Helm
--------
Armour: 147
Evasion Rating: 134
--------
Requirements:
Level: 70
Str: 70 (unmet)
Dex: 70 (unmet)
--------
Item Level: 71
--------
+31 to Accuracy Rating
+19% to Fire Resistance
+35% to Cold Resistance
+15% to Lightning Resistance
</details>

### Screenshot
![image](https://github.com/user-attachments/assets/dd94af11-bb76-4412-ad68-30fe0f4678bc)
![image](https://github.com/user-attachments/assets/8b1688fd-2ad5-40d9-bbb6-46d5a7d99696)

**Comment by Bolado** [comment]
"enabling" and then disabling again seems like fixes the issue.

**Comment by Brasolis** [comment]
Same issue here.

**Comment by Kvan7** [comment]
Can you confirm that, before hitting search, when the price check is open and builtin is OFF the "trade" button looks as follows:
![image](https://github.com/user-attachments/assets/2caa8adb-4a91-4ece-ba8e-ec96362dd00d)
And NOT like this:
![image](https://github.com/user-attachments/assets/86ca71ad-4b92-4a45-84cc-b6c96f7732bd)
Notice the line (difference is on the left half of the one with the line it opens in builtin browser but right half is the user's default browser. disabling the option should make it always open in default browser)

I will double check in the code and see if the error message browser one is reading the setting though. If it is super easy to fix then I will, but as a standard right now I'm not fixing bugs from the original awakend while I'm still getting everything working

**Comment by Shaloum** [comment]
Right after opening overlay with builtin OFF it looks like this.
![image](https://github.com/user-attachments/assets/987ddb3b-f8bb-4cea-a4e2-3f6413c8cfe4)
After executing price check this button disappears.
![image](https://github.com/user-attachments/assets/3f3f36c2-68a1-4e5c-b8d7-55ab344de553)

**Comment by Kvan7** [comment]
yeah, it disappearing is normal. I'll just need to check the error message browser button. That being said you should be able to re-price-check the item and apply the previous filters you had, then instead of hitting search, hit the 'trade' button to open in default browser. not the nicest solution but it should work as a way to get around the current problem

**Comment by Kvan7** [comment]
Should be fixed in v0.1.4 make a new issue if you find a spot where it doesn't respect this setting. (I have only found it not working correctly in the error messages so far)

**Comment by Kvan7** [comment]
This is reverted in next patch. that opening in builtin regardless of setting is for purpose of debugging
