### ISSUE TITLE
Nothing is working at all... any help much appreciated ~

### ISSUE THREAD

**Issue by cimdy** [Kvan7/Exiled-Exchange-2#104]
I did not make it work properly as you requested, and any hotkeys did not respond in the game. I returned to POE1 and found that my config file seemed to be broken. Please attach a usable config instead of obtaining it from another software file, ty gl！

**Comment by cimdy** [comment]
[https://github.com/SnosMe/awakened-poe-trade/issues/1456](url)
This is a similar issue in APT, and it's frustrating that I don't have any friends who can copy files, and the APT downloaded and installed again will not give me the config file~

**Comment by Kvan7** [comment]
there is a default config linked on this [comment](https://github.com/Kvan7/Exiled-Exchange-2/issues/85#issuecomment-2549868603.
If that doesn't fix the issue, I'm  not fully sure what is causing the corrupted data. If it was a bug in awakened, then at this time I'm not fixing the originals bugs, so it will probably have to wait a bit. Sorry for the inconvenience.

**Comment by cimdy** [comment]
Thank you for your help, even though it didn't work. I think I need to consider my own issues.
