### ISSUE TITLE
[PoE2] Missing Total / Elemental DPS on weapon

### ISSUE THREAD

**Issue by cowsay** [Kvan7/Exiled-Exchange-2#109]
When a weapon has a flat elem, it doesn't count anywhere. We only see "Physical DPS".

**Expected behavior**
To see "Total DPS" (and probably have it checked by default).
To see "Elemental DPS" sum, probably. But also have ability to check targeted element (for example flat cold is very valuable for Freeze Buildup).

![{2326B608-43F7-4A4A-8204-3847E3B1FE6C}](https://github.com/user-attachments/assets/ba2abb5b-197b-4b5e-8bbd-75ebf04f90af)

![{FFF15A13-56B6-448B-81C4-ED0FA0C5D9F0}](https://github.com/user-attachments/assets/0920a6b3-1667-4bae-b54e-e93f5b041372)

```Item Class: Bows
Rarity: Rare
Carrion Bane
Advanced Zealot Bow
--------
Physical Damage: 134-224 (augmented)
Cold Damage: 40-61 (augmented)
Critical Hit Chance: 5.00%
Attacks per Second: 1.41 (augmented)
--------
Requirements:
Level: 62
Dex: 142
--------
Sockets: S S 
--------
Item Level: 79
--------
40% increased Physical Damage (rune)
--------
73% increased Physical Damage
Adds 17 to 36 Physical Damage
Adds 40 to 61 Cold Damage
17% increased Attack Speed
+18 to Dexterity
Gain 15 Mana per Enemy Killed
```

**Comment by Kvan7** [comment]
```
Item Class: Two Hand Axes
Rarity: Magic
Crackling Timber Axe of the Lynx
--------
Two Handed Axe
Physical Damage: 48-99
Elemental Damage: 7-117 (augmented)
Critical Strike Chance: 5.00%
Attacks per Second: 1.25
Weapon Range: 1.3 metres
--------
Requirements:
Level: 41
Str: 97
Dex: 45
--------
Sockets: R-R R 
--------
Item Level: 70
--------
+15 to Dexterity
Adds 7 to 117 Lightning Damage
```

**Comment by Kvan7** [comment]
Should be doable, but more challenging than I thought, PoE1 provided us the ele damage but here we get it split out.

**Comment by Kvan7** [comment]
That wasn't that bad, this will be in next release
