### ISSUE TITLE
Minimizes on Fullscreen

### ISSUE THREAD

**Issue by bgastaldo** [Kvan7/Exiled-Exchange-2#114]
### Description

Currently if I am in fullscreen and I price check, if I hover over the Exiled Exchange window it minimizes the whole game and can not use. It works with borderless but borderless makes my frames a lot worse. Is there a way to use this in fullscreen or is it borderless only? Thank you!

**Comment by Kvan7** [comment]
See [requirements](https://kvan7.github.io/Exiled-Exchange-2/download)

**Comment by Kvan7** [comment]
Fullscreen is not currently planned, I could consider in the future but tbh will probably not happen. Sorry for the inconvenience .
