### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by friikadello** [Kvan7/Exiled-Exchange-2#118]
### Description
***Describe what you are experiencing (or other stuff)***
Virus detected in chrome downloader
### Reproduction steps
***Steps to reproduce, if needed***
Click download windows installer
### Screenshot
***Attach screenshot if applicable***
![image](https://github.com/user-attachments/assets/93c03acb-2444-4f5a-b72d-631af8cccd9e)

**Comment by Kvan7** [comment]
See #38 #97.
