### ISSUE TITLE
[PoE2] no option to change from divine currency to exalt in price check

### ISSUE THREAD

**Issue by nedudej** [Kvan7/Exiled-Exchange-2#119]
there is no option to change from div to exalt currency
![Zrzut ekranu 2024-12-19 135739](https://github.com/user-attachments/assets/10cc4494-8c85-47f6-a67c-0011ce225f49)

**Comment by Kvan7** [comment]
Related #29, different enough though that I'm fine keeping as an issue

**Comment by Kvan7** [comment]
The specifically described one should be working so will be in next release
