### ISSUE TITLE
[PoE2] - Missing Anoints

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#121]
**Describe the problem**
Dont have anoint stuff working probably? haven't gotten an anointed item so I cant test

**To Reproduce**

**Expected behavior**
![image](https://github.com/user-attachments/assets/71a61471-adce-4945-ba66-4f97d9cfb568)

**Screenshots**
If applicable, add screenshots to help explain your problem. This is very helpful for comparing the PoE1 vs 2 problems

**Comment by Kvan7** [comment]
I need an item text or two that have anoints so i can test this. 

<details>
<summary> spoilers </summary>

I don't have any :( still act 3 cruel :( 

I have poe2 running when doing dev stuff, so you can guess how much time has gone into this xD

![image](https://github.com/user-attachments/assets/153003f6-3068-403c-8cd3-ea0e0a72fa28)
</details>

**Comment by liakhspace** [comment]
Item Class: Amulets
Rarity: Rare
Vengeance Noose
Amber Amulet
--------
Requirements:
Level: 65
--------
Item Level: 82
--------
**Allocates Subterfuge Mask (enchant)**
--------
+14 to Strength (implicit)
--------
+40 to maximum Energy Shield
24% increased maximum Energy Shield
25% increased Rarity of Items found
+24 to Intelligence
+45% to Fire Resistance
+40% to Cold Resistance

**Comment by ChipsetZ** [comment]
Item Class: Amulets
Rarity: Unique
The Everlasting Gaze
Azure Amulet
--------
Item Level: 78
--------
Allocates Piercing Shot (enchant)
--------
25% increased Mana Regeneration Rate (implicit)
--------
+50 to maximum Mana
50% increased Mana Regeneration Rate
Gain 23% of Maximum Mana as Extra Maximum Energy Shield
--------
What they saw was what they believed, and
they believed Lunaris had not abandoned them.

**Comment by ChipsetZ** [comment]
by any chance how do I test clipboard items while in dev mode?

**Comment by Kvan7** [comment]
shift + space to open the overlay, on the main widget there is a paste field

**Comment by Kvan7** [comment]
Sorry I've been busy so I still haven't gotten to testing these yet

**Comment by Kvan7** [comment]
This is fixed in #170, and will be in next release
