### ISSUE TITLE
PoE Overlay II

### ISSUE THREAD

**Issue by jylep** [Kvan7/Exiled-Exchange-2#122]
### Description
@Kvan7  ***With PoE Overlay II out the effort of converting Awesome Poe Trade is lessened***
***Could be a source of inspiration as well but they are a quite bigger team :)***

**Comment by Kvan7** [comment]
Sorry I'm not quite sure what you are asking or suggesting? The grammar of the sentence doesn't quite make sense. Could you also provide links to PoE Overlay II and Awesome Poe Trade? There seem to be many github repos and I don't know quite which ones you are referring to
