### ISSUE TITLE
fix electron net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#13]
Launching overlay from exe instead of though npm causes all network requests to be blocked somewhere??

- Have tried running same state from API tester, bruno
    - dev headers & prod headers work
- Logging all related info
- Dev and prod body is the same
- `net.request` from electron is called
- listener goes to the 'error'

**Comment by Kvan7** [comment]
This is the cause of #8

**Comment by Kvan7** [comment]
- Tried resetting to upstream and building, local still didn't work(which is strange)
- Reset to upstream and changed version+name, also didn't work
- Reset main back to dev

**Comment by Kvan7** [comment]
Problem seems to be that requests to pathofexile.com are not being made when the program is running in prod mode.
When running from `npm run dev` everything works perfectly but using the electron installer from `npm run package`, the installed application does not make any requests to pathofexile.com for some reason. 

Not as in they aren't in the code, the network dev tool shows request going out to `/proxy/www.pathofexile.com/api/trade2/search/Standard` which is correct and this happens on both prod and dev. But monitoring the port with WireShark, when on a dev build running from either vscode or bash, a HTTP: Client Hello (SNI=www.pathofexile.com)  is made by dev but not prod

More curiously prod makes requests that are successful to github and githubusercontent, (similarly starting with the Client Hello) which succeed. No request is made to www.pathofexile.com though on prod build.

**Comment by Kvan7** [comment]
Added a debug that just pings the host before forwarding the request via proxy. Seems that all hosts are reachable, www.pathofexile.com was just fine and reachable with pings:
```
Pinging www.pathofexile.com [000.000.000.000] with 32 bytes of data:
Reply from 000.000.000.000: bytes=32 time=1ms TTL=57

Ping statistics for 000.000.000.000:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 1ms, Maximum = 1ms, Average = 1ms

[11:01:40 PM] error [cors-proxy] net::ERR_BLOCKED_BY_CLIENT (www.pathofexile.com)
[11:01:40 PM] ping success [www.pathofexile.com] 
```

**Comment by Kvan7** [comment]
Double checked the stringified `net.request` are exactly the same and both work and retrieve a response in bruno

**Comment by Kvan7** [comment]
errors in dev tools are:
```
Failed to load resource: net::ERR_EMPTY_RESPONSE
index-BB9h9Seq.js:22 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at bT.proxy (index-BB9h9Seq.js:22:22121)
    at o (index-BB9h9Seq.js:35:43117)
    at index-BB9h9Seq.js:35:44264
    at Qi (index-BB9h9Seq.js:4:656)
    at ai (index-BB9h9Seq.js:4:735)
    at Array.g (index-BB9h9Seq.js:4:10859)
    at Wu (index-BB9h9Seq.js:4:1981)
    at Qc (index-BB9h9Seq.js:4:2032)
    at O (index-BB9h9Seq.js:4:42884)
    at mount (index-BB9h9Seq.js:4:29714)
```

**Comment by zedicuszulzoran** [comment]
<img width="577" alt="image" src="https://github.com/user-attachments/assets/bcbb3f7b-09f4-4628-a161-bfc8efbb276e">
I figure i may be wrong, but it wouldn't be because the config file is named wrong would it? 
the file in the app is named >
<img width="657" alt="image" src="https://github.com/user-attachments/assets/5e78b355-4145-4d23-8288-52db6a9862b6">

**Comment by Kvan7** [comment]
You are correct that is a bug, but changing it does not appear to fix the problem. Thanks for spotting that though!

**Comment by Kvan7** [comment]
The main problem with this right now is that it is a problem in prod but not in dev. When I work on this tonight I will try to build without optimizations and see it that is causing it. 

I think right now I need to come up with a way to reproduce this issue when running the application in vscode so I can try and debug it easier.

**Comment by Kvan7** [comment]
I may need to look into if there is some settings with electron that start rejecting http requests when, maybe the name of the application changes?? That would be the only main difference, as far as I can tell. 

Oh it could also be a node version problem, that would explain why building my the upstream locally was still breaking. I will probably try this first, since that may actually make sense. Right now I'm on v20 so I'll see if I can tell if upstream was on 18, although the package.json previously showed engine >=20 if I remember correctly.

**Comment by Kvan7** [comment]
Uuhhhhggg if this was the problem the whole time I'm going to not be happy, but also happy at the same time :) 

https://github.com/SnosMe/awakened-poe-trade/actions/runs/12256606490/job/34192233814#step:3:1

Node version is different. Upstream is on v18. Will try this tonight

**Comment by Barragek0** [comment]
I'm not experienced with typescript, but I also looked into this pretty extensively yesterday and couldn't find what the issue was.

**Comment by hakastein** [comment]
CORS error is a browser security error, that's mean that your domain ( from what requests are made is not in the whitelist ) 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors

It's can bypassed by proxying queries somehow. 

So in example:
You can access some url by curl or nodejs or everything else, but you can' access same URI in browser because browser won't allow you to do this.

**Comment by hakastein** [comment]
And, for that reason there is [proxy.ts](https://github.com/SnosMe/awakened-poe-trade/blob/master/main/src/proxy.ts), i don't know how it worked before, but looks like you need to replace net.request in this part of code

```ts
const proxyReq = net.request({
        url: 'https://' + req.url.slice('/proxy/'.length),
        method: req.method,
        headers: {
          ...req.headers,
          'user-agent': app.userAgentFallback
        },
        useSessionCookies: true
      })
 ```
 to something in node side, or just disable CORS completely in electron https://github.com/electron/electron/issues/23664#issuecomment-631674094 (but it's bad decision and probably doesn't work now)

**Comment by hakastein** [comment]
There is how other tools in electron making this

https://github.com/CorySanin/Kitten-for-CSGO/blob/f9435fc8f8bb54f9407a4274aaa5ee3cd1f3fbd0/main.js#L162

```js
const request = require('request')
//...
ipc.on('inviteUrl', function (event, steamid){
  request('https://steamcommunity.com/profiles/' + steamid, function(err, resp, body){
    if (!err && resp.statusCode === 200) {
      let dom = new JSDOM(body, { runScripts: "outside-only" })
      let joinBtn = dom.window.document.querySelector('.profile_in_game_joingame a');
      event.sender.send('inviteUrl', (joinBtn !== null)?joinBtn.href:'')
    }
  })
  ```

**Comment by Bennnsen** [comment]
Also started it locally earlier. For me it used the port 5173. in /main/src/server.ts in line 118 there is port 8584 metioned. Don´t want to spread confusion. Could that also be related?

**Comment by hakastein** [comment]
But this isn't your biggest problem. Your problem is [items.ndjson](https://github.com/SnosMe/awakened-poe-trade/blob/master/renderer/public/data/en/items.ndjson) (and other ndjson files ofcourse). You need fill those files to make it work. And for it you need parse game dat file. Probably this https://github.com/SnosMe/poe-dat-viewer can help you.

**Comment by hakastein** [comment]
> Also started it locally earlier. For me it used the port 5173. in /main/src/server.ts in line 118 there is port 8584 metioned. Don´t want to spread confusion. Could that also be related?

it's not, request are catched by proxy, but not processed correctly for some reason.

**Comment by Kvan7** [comment]
Downgraded node to v18.20, that doesn't seem to fix the problem. 

> or just disable CORS completely in electron [electron/electron#23664 (comment)](https://github.com/electron/electron/issues/23664#issuecomment-631674094) (but it's bad decision and probably doesn't work now)

Disabling cors completely as described in this didn't fix it either. which probably means it either isn't cors or that cli flag for electron doesn't work anymore.

**Comment by Kvan7** [comment]
The things that I cannot understand at this point are:
- why it *is* working in npm run dev, but not the electron build.
- why are the upstream's builds working then?
- why when reverting to the latest upstream commit and building that it also doesn't work

**Comment by Kvan7** [comment]
I double checked the contents of the actions logs, they are exactly the same line for line, save names and checksum hashes:
https://github.com/Kvan7/Exiled-Exchange-2/actions/runs/12288946670/job/34293595475
https://github.com/SnosMe/awakened-poe-trade/actions/runs/12256606490/job/34192233814

**Comment by Kvan7** [comment]
Other one that I could conceivably think is that electron somewhere still thinks it is awakened, and is seeing requests that "aren't from it" so it is just shooting them all down? Then again that should have been fixed by building when on the same commit as upstream.

**Comment by Barragek0** [comment]
> Other one that I could conceivably think is that electron somewhere still thinks it is awakened, and is seeing requests that "aren't from it" so it is just shooting them all down? Then again that should have been fixed by building when on the same commit as upstream.

Have you tried taking a fresh copy of awakened source code, recompiling it and rebuilding it in the same way you're building this modified fork? If that does work correctly when compiled and pushed and this doesn't it must be one of the changes that's been made, then you could take that fresh fork, apply a change or two at a time, then know exactly whats causing it. I would do this, but again, im not familiar with electron and have no idea how to build it.

**Comment by Kvan7** [comment]
Yeah, i just thought of that I am currently cloning and building from scratch awakened

**Comment by Kvan7** [comment]
No, same error, which implies it's an environment issue. But there shouldn't be any environment issues through github actions. So that is really confusing.

I'm going to fork it again and make no changes and run actions to see if that works

**Comment by Kvan7** [comment]
Alright github actions are kicking my butt. It is late, and I require sleep I think. I'll see if I can try again before work, but will definitely try some more tomorrow night

**Comment by Kvan7** [comment]
If anyone knows the electron publish stuff more, feel free to let me know why that isn't working, I have a list of steps that work on this repo to do it correctly but following those steps on the test is not working for some reason.

Either way I just gave up and added an upload artifacts step so I can at least download the dist myself manually

**Comment by Kvan7** [comment]
Tested with that setup.exe and getting same error. going to try to reset the test repo back again but keeping the artifact upload so i can test the closest version

**Comment by Kvan7** [comment]
After completely resetting and building, still not working. If anyone wants to double check here is the [repo](https://github.com/Kvan7/awakened-poe-trade) This will be deleted in 2 days since it serves no purpose



> Could you share the working steps?

You mean the list of steps to release?
I'll commit that to `DEVELOPING.md` in a sec, if not that let me know what steps you mean

**Comment by Kvan7** [comment]
Added in https://github.com/Kvan7/Exiled-Exchange-2/blob/master/DEVELOPING.md @jylep

**Comment by Kvan7** [comment]
So recap of right now since this issue is quite long, 
Currently if you install `Awakened-PoE-Trade`(original repo) it works, and you don't get `net::ERR_BLOCKED_BY_CLIENT` for any proxied request.

Cloning that repository and running a build via github actions(in theory the same env), those artifacts cause `net::ERR_BLOCKED_BY_CLIENT ` for some reason. 

Possible options I see right now:
- the `exe`s uploaded to the releases on `Awakened-PoE-Trade`(original repo) are *not* the same `exe`s built by github actions?
    - could this be verified by checksums? not sure how that would work
- There is some sort of check that it was built by the original repo somewhere? 
    - this would probably be something that electron is doing
    - I can't find *any* evidence of this
- Looks like latest release of  `Awakened-PoE-Trade`(original repo) is still from Aug 2 so there is the possibility that the main branch is just broken rn?
    - **Going to look into this next**

At this point in time, I do not think this is a `cors` error, looking at the [code](https://github.com/Kvan7/Exiled-Exchange-2/blob/f7d686291f13d70f62e94090acb656be6d7a83ec/main/src/proxy.ts#L48), we are just prepending any error from requesting a url in proxy with `error [cors-proxy]` so that doesn't necessarily mean it is a `cors` error just an error from the proxy to get around cors problems

**Comment by Juventinos** [comment]
to be honest, i have no idea about this error or code at this lvl, but why don't you try chatgpt maybe have some idea :D 
just trying to help, nothing more

**Comment by Kvan7** [comment]
>     * Looks like latest release of  `Awakened-PoE-Trade`(original repo) is still from Aug 2 so there is the possibility that the main branch is just broken rn?
>       

YES YES YES, latest commit on upstream is just broken!!!!!!!

I'm NOT completely insane YAY!

(now i have to more or less restart but at least it *should* work?)

**Comment by Kvan7** [comment]
Upstream building from tag `v3.25.102` works without errors when built from github actions

**Comment by Kvan7** [comment]
I do have to go to work now, so I'll start that later tonight

**Comment by Kvan7** [comment]
Ahh ok, I'm going to look into how "unsafe" that makes the program, if it isn't super bad I may just do that. 


> Either way for now poe.ninja should be skipped because it does not contain PoE2 related information

Yeah I'll make an issue for it, right now this has been priority 1 and next up is fixing price checking

**Comment by Kvan7** [comment]
I had some free time so I looked at the different referrer policies, seems that only unsafe and no-referrer-when-downgrade are working without the error. Of the two I would obviously use the no referrer one, but that being said I do not know basically anything about the security problems with all the referrer policies. Still in the air if this is a solution or just a temporary fix
