### ISSUE TITLE
"#% to all Elemental Resistances" not working properly as a pseudo mod

### ISSUE THREAD

**Issue by DubmasterxD** [Kvan7/Exiled-Exchange-2#132]
The app creates a pseudo mod for this as 3x total elemental resistances, so for example "+10% to all Elemental Resistances" mod is being searched as "30% total Elemental Resistance". 
But the query is incorrect, if I press "trade" button to check this search in poe2 trade site, I can see that it's only counted as 10%, because the weight of "#% to all Elemental Resistances" is set to 1 instead of 3 in weighted sum filter

**Comment by Kvan7** [comment]
That makes sense. I think I just had a slight oversight with that since the UI overlay was showing the correct number but I didn't check the actual query. 
Thanks for the report!

**Comment by Kvan7** [comment]
Debating if I can do a patch with this right now. I'm not sure just from how the build pipeline works, but I could probably get this out tonight

**Comment by 2131242** [comment]
Yeah just came here to write this you just need to do it this way
![image](https://github.com/user-attachments/assets/d22b9043-cf8d-47d4-b692-dba8ecae0732)

**Comment by Kvan7** [comment]
yeah i just have to go change the weights which is a 1 line change for each in a json file. The second one is something else and will stay. That is for when you instead want to do total cold res instead, and since all ele contributes to the total cold it should stay there, but that one obviously won't get the  3 weight since we only care about the cold

**Comment by Kvan7** [comment]
The fix is done I'm just at work so i can't test and publish, and I would rather test it and the build to ensure it works instead of releasing completely untested code, even though it is 100% going to be fine
