### ISSUE TITLE
Korean Search Not working

### ISSUE THREAD

**Issue by koojongin** [Kvan7/Exiled-Exchange-2#134]
![image](https://github.com/user-attachments/assets/9b1f48f8-28b6-4562-b7fe-c0ef3e5f23cb)

![image](https://github.com/user-attachments/assets/a79a81cb-7daf-4bcf-bcc5-08384d85abca)

**Comment by Kvan7** [comment]
Languages besides English do not currently work. This is in progress and it's status is being reported under [this milestone](https://github.com/Kvan7/Exiled-Exchange-2/milestone/3)

**Comment by Kvan7** [comment]
This should be mostly working in the latest release
