### ISSUE TITLE
Overlay disappears after moving mouse cursor off item

### ISSUE THREAD

**Issue by Chromos-Def** [Kvan7/Exiled-Exchange-2#136]
I use ctrl+d to open the price check menu. As long as cursor stays on the item it will keep the overlay active. It disappears soon as I move my mouse cursor off the item. The hovered tooltip of the item stays stuck on the screen until I click/tab out of PoE 2.

It should function as it did in PoE 1 yeah? Able to click on the overlay and change options and such from there.

**Comment by Kvan7** [comment]
Go into settings > price check > auto hide off

See if your keybind is set to the one for just opening it or the auto hide off one.

I personally don't use the default and just use ctrl+d with auto hide off since i find the moving cursor off the item and it disappearing really annoying too

**Comment by Kvan7** [comment]
I would provide a picture but I'm on a laptop that doesn't have poe2 installed :( sorry

**Comment by Chromos-Def** [comment]
There isn't an option in price check that says auto hide off.

![image](https://github.com/user-attachments/assets/dac71fa8-42ac-481b-ac50-4bcdfe203956)

The auto search keybinds were both enabled by default.

**Comment by Kvan7** [comment]
My bad, it's probably in hotkeys then? Let me look if i have a screenshot somewhere

**Comment by Chromos-Def** [comment]
![image](https://github.com/user-attachments/assets/5daa5454-47d4-4172-b88a-f02dd5f4df49)
Found it!!! This is how I had it set in poe 1 forever. Is it default with auto hide in poe 1 as well?

Thanks! That was driving me mad.

**Comment by Kvan7** [comment]
Glad that worked!

Yeah the default is to have auto hide enabled for some reason? not really sure why but I'm guessing the orignal dev had a good reason.

**Comment by message** [comment]
Same issue for me. Why it happens? What did you change compared to Awakened PoE upstream? 

If I launch Awakened PoE, it works as expected.

Awakened PoE:

https://github.com/user-attachments/assets/0588618e-84f8-4269-b0e5-824db6b60eb5

Exiled Exchange:

https://github.com/user-attachments/assets/e719a598-69de-4469-bb19-49583f65d70c
