### ISSUE TITLE
[Not Recognized Modifier] - +2 Charm Slots

### ISSUE THREAD

**Issue by ezbooz** [Kvan7/Exiled-Exchange-2#137]
## Not Recognized Modifier
***Maelström Tether  /   Belt***
`+2 Charm Slots`

```
Item Class: Belts
Rarity: Rare
Maelström Tether
Plate Belt
--------
Charm Slots: 3 (augmented)
--------
Requirements:
Level: 51
--------
Item Level: 74
--------
+111 to Armour (implicit)
--------
+2 Charm Slots

```

![image](https://github.com/user-attachments/assets/57bef355-499d-4c99-b8f0-de963452da1c)

**Comment by Kvan7** [comment]
oh, yeah haven't been able to test that. Thanks for the report! I'll get that fixed for the next release!
