### ISSUE TITLE
Recognised as virus by windows defender

### ISSUE THREAD

**Issue by Exero46** [Kvan7/Exiled-Exchange-2#138]
### Description
***Describe what you are experiencing (or other stuff)***
[Exiled-Exchange-2-Setup-0.1.3.exe](https://github.com/Kvan7/Exiled-Exchange-2/releases/download/v0.1.3/Exiled-Exchange-2-Setup-0.1.3.exe) is blocked by windows defender 

Windows defender is claiming it detected "Trojan:Win32/Wacatac.H!ml"
### Reproduction steps
***Steps to reproduce, if needed***
download Exiled-Echange-2-Setup-0.1.3.exe with windows defender on.

### Screenshot
***Attach screenshot if applicable***

**Comment by Kvan7** [comment]
see #38 #97

**Comment by Kvan7** [comment]
Specifically, I don't know enough about AV to know how to stop it from showing up as a false positive. If it is a big concern feel free to check the changes from the upstream and build yourself.
