### ISSUE TITLE
[Parse Error] - Andvarius

### ISSUE THREAD

**Issue by chewbacca2314** [Kvan7/Exiled-Exchange-2#140]
## Parse Error
Andvarius

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
Item Class: Rings
Rarity: Unique
Andvarius
Gold Ring
--------
Requirements:
Level: 40
--------
Item Level: 77
--------
13% increased Rarity of Items found (implicit)
--------
55% increased Rarity of Items found
+10 to Dexterity
-20% to all Elemental Resistances
--------
Danger is the price of wealth.


```
![image](https://github.com/user-attachments/assets/c083bc77-7569-44d4-9228-af8b4963c5b3)
![image](https://github.com/user-attachments/assets/66e3754f-dc78-4099-8fc6-5dc5efbe2d2c)
it parses description, and the item stats only available in "hidden"

**Comment by Kvan7** [comment]
Thanks for the report! At this time, unique items are currently not supported. This is in progress but probably will happen after localization support is added. Sorry for the inconvenience!
