### ISSUE TITLE
[Parse Error] - Arvil's Wheel Hardwood Targe

### ISSUE THREAD

**Issue by kt92** [Kvan7/Exiled-Exchange-2#145]
## Parse Error
***Arvil's Wheel Hardwood Targe***

```
Item Class: Shields
Rarity: Unique
Arvil's Wheel
Hardwood Targe
--------
Block chance: 36% (augmented)
Armour: 16 (augmented)
Evasion Rating: 11 (augmented)
--------
Sockets: S 
--------
Item Level: 67
--------
46% increased Block chance
63% increased Armour and Evasion
Lose 1% of Life on Kill
Lose 1% of Mana on Kill
49% increased Skill Effect Duration
--------
The unending carnage of war
mercilessly grinds away
at body and mind.

```

![image](https://github.com/user-attachments/assets/d880afe9-fb27-4b24-9425-cb7296d7a1d6)

**Comment by Kvan7** [comment]
Thanks for the report! At this time, unique items are currently not supported. This is in progress but probably will happen after localization support is added. Sorry for the inconvenience!

**Comment by Kvan7** [comment]
Looking at this one a bit though, uniques usually parse but just have basically all mods as "unrecognized", this specifically seems to be a data problem where this particular unique doesn't have a trade id attached in the `items.ndjson` file for some reason.

**Comment by Kvan7** [comment]
I'm probably going to attach this bug to the `Uniques` milestone and tackle it when I start work on the uniques overall.

**Comment by Kvan7** [comment]
Uniques should now be working, Hmm, this one still isn't for some reason though. I'll need to look into it specifically more. Maybe related to #154

**Comment by Kvan7** [comment]
stat `Lose 1% of Life on Kill` -> matcher: `Lose #% of Life on Kill`. does not exist on trade site.

**Comment by Kvan7** [comment]
guessing this is a not rolled value on the shield?

**Comment by Kvan7** [comment]
yep and even worse it does exist its just as a negated recover life on kill. this is fixable it seems
