### ISSUE TITLE
Not an issue just a suggestion

### ISSUE THREAD

**Issue by HarveyK1** [Kvan7/Exiled-Exchange-2#155]
### Description
***Describe what you are experiencing (or other stuff)***

There weren't any options for suggestions so my bad.

Was going to suggest a way of changing the price of an item you are price checking like from div to ex and ex to div, because some items are 1d but their actual price would be half of 1div but wont show since 1 is less than the higher price in ex if that makes sense. So it gets a little annoying to then go check what the price actually is in exatls

**Comment by Kvan7** [comment]
You can filter the results by ex or div, just a sec I'll see if I have an image of that

**Comment by Kvan7** [comment]
From the original but I switched the chaos part to instead be ex, so you can do any currency, ex, or divs
![image](https://github.com/user-attachments/assets/d287ed92-d6e5-4948-b80b-d91ba1bb7041)

Let me know if this was what you were asking about

**Comment by HarveyK1** [comment]
Ah, yea i did mean that didnt know that was a there tbh thanks

**Comment by Kvan7** [comment]
Sounds good! Glad that is solved!
