### ISSUE TITLE
Is there any chance to support macOS?

### ISSUE THREAD

**Issue by ansonsiva** [Kvan7/Exiled-Exchange-2#159]
I'm using crossover to play POE2 on mac.
Is there any chance exiled-exchange-2 to support macOS soon?

**Comment by Kvan7** [comment]
Mac is currently supported with the Darwin build. https://github.com/Kvan7/Exiled-Exchange-2/releases/tag/v0.1.3

**Comment by ansonsiva** [comment]
> Mac is currently supported with the Darwin build. https://github.com/Kvan7/Exiled-Exchange-2/releases/tag/v0.1.3

crashed immediately...
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/9ee09970-081d-431e-b868-7d5bc5cb3e83" />

**Comment by ansonsiva** [comment]
Problem solved.
I resign the app using this command.
sudo codesign --force --deep --sign - /Applications/Exiled\ Exchange\ 2.app
