### ISSUE TITLE
I would like to propose a feature.

### ISSUE THREAD

**Issue by koojongin** [Kvan7/Exiled-Exchange-2#171]
Korean trade websites are often down or slow.
I wish this app could support a feature like Sidekick's English exchange search functionality.
Even if the app settings are in Korean, it would be great if the trade API could search using English trade websites.

**Comment by Kvan7** [comment]
I'm not currently doing _new_ features, but I think this makes sense and wouldn't probably be too hard to add. Just note that if you are still listing items on the Korean site, then the difference in prices would potentially lead to some confusion. If i do get to implementing this would be basically a setting under the language setting.
