### ISSUE TITLE
[Parse Error] - Grim Pile Advanced Barrier Quarterstaff

### ISSUE THREAD

**Issue by santiagomburroni** [Kvan7/Exiled-Exchange-2#172]
## Parse Error
Grim Pile Advanced Barrier Quarterstaff

### Item Text
```
Item Class: Quarterstaves
Rarity: Rare
Grim Pile
Advanced Barrier Quarterstaff
--------
[Quality]: +20% (augmented)
[Physical] Damage: 151-252 (augmented)
[ElementalDamage|Elemental] Damage: 20-29 (augmented), 2-43 (augmented)
[Critical|Critical Hit] Chance: 10.00%
Attacks per Second: 1.63 (augmented)
--------
Requirements:
Level: 62 (unmet)
[Dexterity|Dex]: 110
[Intelligence|Int]: 44
--------
Sockets: S S 
--------
Item Level: 75
--------
Adds 2 to 43 [Lightning|Lightning] Damage (enchant)
--------
40% increased [Physical] Damage (rune)
--------
+13% to [Block] chance (implicit)
--------
116% increased [Physical] Damage
Adds 20 to 29 [Fire|Fire] Damage
+81 to [Accuracy|Accuracy] Rating
16% increased [Attack] Speed
+3 to Level of all [Melee|Melee] Skills
+8 to [Intelligence|Intelligence]
--------
[Corrupted]

```

Additional data: this happens when price checking any non-currency item from chat. uniques get assigned their correct unique name on the top left, but every line on the item gets interpreted as a not recognized modifier.
Price checking items directly on my stash, inventory, vendor, or trade window works perfectly.

Tool output:
![image](https://github.com/user-attachments/assets/830b7968-2b75-42ba-93cc-e2c2562fc925)

**Comment by Kvan7** [comment]
yeah duplicate of #71, this is a poe2 bug right now. I'm currently not looking into implementing a workaround yet, I have a couple other things that I want to get working first

**Comment by santiagomburroni** [comment]
missed it when looking at the bug list, my bad. I am unfamiliar with the codebase but would love to take a look at things and see if i can make it work somehow. If so i'll submit a PR. cheers and thanks for the swift response!

**Comment by Kvan7** [comment]
> I am unfamiliar with the codebase but would love to take a look at things and see if i can make it work somehow. If so i'll submit a PR. cheers and thanks for the swift response!

I'll writeup what would probably need to happen to fix this in 71 when I get some time. Due to the bug there would be a couple of things that would be quite different and need to change
