### ISSUE TITLE
[Japanese] Add support for language

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#184]
Should be:

- [x] Add `ja` / [app_i18n.json](https://github.com/Kvan7/Exiled-Exchange-2/blob/dev/renderer/public/data/en/app_i18n.json)
- [x] Add `ja` / [client_strings.js](https://github.com/Kvan7/Exiled-Exchange-2/blob/dev/renderer/public/data/en/client_strings.js)
- [x] Get tables from game in langauge
- [x] get trade site static json 
- [x] add ja to all langauge build 
- [x] add Japanese trade site 
- [x] add Japanese language 
- [ ] Other stuff? - probably a bunch more

**Comment by KazumaIgarashi** [comment]
- `ja`
https://jp.pathofexile.com/api/trade2/data/filters
https://jp.pathofexile.com/api/trade2/data/items
https://jp.pathofexile.com/api/trade2/data/static
https://jp.pathofexile.com/api/trade2/data/stats

**Comment by Kvan7** [comment]
Most now done, currently dealing with a dependency upgrade caused by having to repoll data files from game data. 

Noticing some problems that will NOT be solveable probably. 
- fake pseudo will not be supported since it depends on old json files that were never generated for new languages. This could be done but it would be fully manually which is not worth the time for, again, something ggg will eventually make obsolete.
- A few other minor problems like above, where they were dependent on originally generated json files.
