### ISSUE TITLE
App ignores ctrl+d while running as admin

### ISSUE THREAD

**Issue by the-s0urce** [Kvan7/Exiled-Exchange-2#190]
App ignores ctrl+d running as admin

If poe2 runs in admin mode, the app needs to run in admin mode too.

But if you run it in admin mode, nothing works, no interaction at all.

**Comment by Kvan7** [comment]
What do the [logs](https://kvan7.github.io/Exiled-Exchange-2/faq.html) show? And also provide os and poe settings (fullscreen setting mainly).
