### ISSUE TITLE
Change Default Overlay Keybind

### ISSUE THREAD

**Issue by Gaudon** [Kvan7/Exiled-Exchange-2#192]
### Description
Every time I type sentences using proper capitalization, I accidentally open the overlay because of the delay/speed of still holding shift while hitting space. This happens frequently when I start a sentence with "I ", everytime.

### Reproduction steps
Try to type a sentence starting with a capital I and not open the overlay (Ie: steam friend messages).

### Screenshot
Not Needed.

If it's *required* that the overlay must have a key bind, absolutely fine. but PLEASE let me change it from shift+space to something else as I've uninstalled this app multiple times out of pure rage and re-installed it out of pure necessity!

Thanks!

**Comment by Kvan7** [comment]
You can already change this
![image](https://github.com/user-attachments/assets/8c06e9b6-328d-4d19-89d2-82eaef30cf91)

**Comment by Gaudon** [comment]
@Kvan7 maybe I'm overlooking something fundamental, but what does that asterisk imply? I've tried changing the overlay bind and it seemingly doesn't do anything. 

I'll try again though shortly! Apologies if this does work and I'm doing it wrong

**Comment by Kvan7** [comment]
Make sure you hit save in the bottom right, otherwise it won't do anything

> what does that asterisk imply? 

Required, just since if you unbind it, you can never open the menu again

**Comment by Gaudon** [comment]
Confirmed I'm an idiot. Was just trying to unbind and assumed it meant it couldn't be changed.

**Comment by Kvan7** [comment]
All good! Glad it worked out!
