### ISSUE TITLE
[Parse Error] - Translate unique problem

### ISSUE THREAD

**Issue by oscarada87** [Kvan7/Exiled-Exchange-2#196]
## Parse Error
***Put name of item here, and in the title***
The unique item in ndjson file has chinese name at `base`, but english at `refName`, so whenever the program call `ITEM_BY_REF` function, it will find nothing, and caused parse error.
There are same problem when using korean or russian.
```
// item in cmn-Hant/items.ndjson
// Base item
{"name": "藍玉戒指", "refName": "Sapphire Ring", "namespace": "ITEM", "icon": "https://webtw.poecdn.com/gen/image/WzI1LDE0LHsiZiI6IjJESXRlbXMvUmluZ3MvUmluZzYiLCJ3IjoxLCJoIjoxLCJzY2FsZSI6MX1d/74a5d719fd/Ring6.png", "craftable": {"category": "Ring"}, "w": 1, "h": 1}
// Unique item
{"name": "極圈", "refName": "極圈", "namespace": "UNIQUE", "unique": {"base": "藍玉戒指"}}
```

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
物品種類: 戒指
稀有度: 傳奇
極圈
藍玉戒指
--------
需求:
等級: 12
--------
物品等級: 80
--------
+28% 冰冷抗性 (implicit)
--------
增加 30% 冰冷傷害
+60 最大魔力
+13 力量
被你擊中而冰緩的敵人，可以像冰凍那樣被粉碎
--------
北方由我統御
循環往復
不斷傳承
高唱梅吉諾德之歌！
```

### Common Question Checklist

- [x] I have checked the [pinned issues and existing issues](https://github.com/Kvan7/Exiled-Exchange-2/issues?q=is%3Aissue) for this problem already
- [x] I have read the [FAQ](https://kvan7.github.io/Exiled-Exchange-2/faq)
- [x] I have read the [Common Issues](https://kvan7.github.io/Exiled-Exchange-2/issues)

**Comment by Kvan7** [comment]
I'm going to get to this tomorrow. 

I after this and other new bug fixed I'm going to go into unittest land probably yay

**Comment by oscarada87** [comment]
Please let me know if there are anything I can help with.
