### ISSUE TITLE
[Fetch Error] - Failed to fetch trade site when using Japanese settings

### ISSUE THREAD

**Issue by KazumaIgarashi** [Kvan7/Exiled-Exchange-2#197]
## Fetch Error
***Put name of item here, and in the title***
currency, rare helmet, charm, etc. (all item?)
It seems that I can't check the price of all items in Japanese settings.

* EDIT: I re-uploaded the screenshot in a later comment.
* EDIT2: Changed the issue title from parse error to fetch error.

Thank you for your help.

### Item Text
***Please provide the item's description***
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
アイテムクラス: 兜
レアリティ: レア
病的な頂き
ベール付きの仮面
--------
回避力: 168 (augmented)
エナジーシールド: 67 (augmented)
--------
装備要求:
レベル: 28
器用さ: 30
知性: 30
--------
アイテムレベル: 33
--------
回避力 +45
最大エナジーシールド +16
回避力およびエナジーシールドが63%増加する
最大ライフ +22
冷気耐性 +18%
```

```
アイテムクラス: スタック可能カレンシー
レアリティ: カレンシー
変成のオーブ
--------
スタック数: 40/40
--------
ノーマルアイテムをモッドを1個持つマジックアイテムにアップグレードする。
--------
このアイテムを右クリックした後、ノーマルアイテムを左クリックして使用する。
Shift+クリックでスタックから取り出す。
```

### Common Question Checklist

- [x] I have checked the [pinned issues and existing issues](https://github.com/Kvan7/Exiled-Exchange-2/issues?q=is%3Aissue) for this problem already
- [x] I have read the [FAQ](https://kvan7.github.io/Exiled-Exchange-2/faq)
- [x] I have read the [Common Issues](https://kvan7.github.io/Exiled-Exchange-2/issues)

**Comment by Kvan7** [comment]
Probably need to change the language in settings

**Comment by KazumaIgarashi** [comment]
I was checking the bug and took the screenshot after switching the settings from Japanese to English, sorry for the confusion.

Once again, I switched the language to "Japanese" and updated the screenshot.

- Rare body armour:
`Trade site request failed Error: failed to fetch`

![body](https://github.com/user-attachments/assets/fd05d119-432d-454d-8d40-67aa2ac0b87c)

- Orb of Transmutation:
`Trade site request failed Error: failed to fetch`

![orb](https://github.com/user-attachments/assets/54a71f2d-c679-4c52-a518-0aa43ba99378)

- Kitoko's Current Jewelled Gloves (unique glove):
```
An error occurred while parsing the item
This is probably a bug and you can report it on GitHub.
```
This may be a parsing error for a unique item, which is also found in other issues.
![kitoko](https://github.com/user-attachments/assets/e095ac0c-a232-4ff2-8455-8dc9781302ff)

**Comment by Kvan7** [comment]
Found it, just missed a line in `main`. will be out next release(today?)

**Comment by KazumaIgarashi** [comment]
What a quick response! It's wonderful, and thank you!
