### ISSUE TITLE
DS_Store scripts update

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#56]
Update DS_Store to have more organized workflow process. 

Current scripts in root of DS_Store, need  to be moved to `scripts` folder and updated for that new location.

Need to add a single script that does the whole of the current pushing if ndjson files stuff so that I don't have to run like 8 npm commands sequentially and can just run that one. This is similar to `npm run make-index-files`. The older commands should still be there incase they are needed.

--------
The current process is to run the following `npm` commands sequentially(inside of .DS_Store)

1. anon-python
2. copy-py-ndjson
3. temp-images
4. push-ndjson

**Comment by manuelstolze** [comment]
Hi, may I ask a question: What is the purpose that the `.DS_Store`  is a hidden folder? Is this necessary?

**Comment by Kvan7** [comment]
No real reason, was just initially not committed but then I added it so it could be changed. I just have had it in the workspace file so I hadn't noticed that I had made it hidden

**Comment by puttehi** [comment]
Look into adding `**/.DS_Store` into `.gitignore` (and moving the contents to proper places and `git rm --cached **/.DS_Store`). It should not be used as a part of a project as it is for MacOS internals created by its Finder application (AFAIK).

On a side-note, for a quick 60 second dive into `.DS_Store` history (and why it is prefixed with a `.`) from the original tech lead of Finder: https://www.arno.org/on-the-origins-of-ds-store

**Comment by Kvan7** [comment]
Unhid the ds_store, for now just removed the dot and added an update script
