### ISSUE TITLE
Update localization for PoE2

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#66]
Currently I have only been working on English since that is what I speak. This _shouldn't_ be that bad since SnosMe did a lot of work for localization already. I just haven't looked at this yet due to rushing to get this in a somewhat working state first.

Tasks:
- [x] #67
- [x] #68
- [x] #69
- [x] #70
- [x] #149
- [x] #150

**Comment by Kvan7** [comment]
Getting many errors that are kinda difficult to resolve. Was trying to add back support for "ru", "ko", "cmd-Hant". This may just require input from users in those languages to get it working.

I believe that so long as the data is pulled, then stuff *should* work???

**Comment by Kvan7** [comment]
`ru`: erroring when pulling data from game files
`ko`: cannot access trade site to get json api data. (seems to exist but redirects to some sign in url thing that is freaking out ublock origin, and I kinda don't want to setup nop rule for it)
`cmn-Hant`: cannot find trade site for this

**Comment by maksim789456** [comment]
> `cmn-Hant`: cannot find trade site for this

Trade page on https://poe.game.qq.com/trade but without auth cannot open page and get access to [api](https://poe.game.qq.com/api/trade/data/stats)
`{"error":{"code":8,"message":"Unauthorized"}}`

**Comment by EasyBabi** [comment]
@Kvan7 I can help on 'KO' localization. Please contact me via github or discord (@easybabi). Thank you.

**Comment by Kvan7** [comment]
> Trade page on https://poe.game.qq.com/trade but without auth cannot open page and get access to [api](https://poe.game.qq.com/api/trade/data/stats) `{"error":{"code":8,"message":"Unauthorized"}}`

I probably still won't be able to access it, but do you know if this is the poe2 trade site or the poe1 one?

**Comment by maksim789456** [comment]
> > Trade page on https://poe.game.qq.com/trade but without auth cannot open page and get access to [api](https://poe.game.qq.com/api/trade/data/stats) `{"error":{"code":8,"message":"Unauthorized"}}`
> 
> I probably still won't be able to access it, but do you know if this is the poe2 trade site or the poe1 one?

I think it's poe1, but I don't found any other links for trade on CN section sites

**Comment by AreChen** [comment]
@Kvan7  I found a GitHub repository for traditional Chinese localization of poe2-trade web, The translation files there might be helpful!

https://github.com/Chuanhsing/poe2-trade-zh/blob/main/js/translate.zh_TW.js

**Comment by KazumaIgarashi** [comment]
@Kvan7 
Hello, I'm a Japanese player.
Japanese has been officially supported in PoE1 for a little while, and in PoE2 since the start of early access, so I'd like to contribute to the localization of this tool.
If there's any data to commit, I'd like to do that. Should I check #68 #69 first? thank you.

**Comment by AreChen** [comment]
> @Kvan7 I found a GitHub repository for traditional Chinese localization of poe2-trade webpage, The translation files there might be helpful!
> 
> https://github.com/Chuanhsing/poe2-trade-zh/blob/main/js/translate.zh_TW.js
> 
> In Poe1, by using awakened-poe-trade + the English poe-trade webpage + the Poe1 version of this plugin(poe-trade-zh), I can perfectly search prices.



> @Kvan7 I found a GitHub repository for traditional Chinese localization of poe2-trade webpage, The translation files there might be helpful!
> 
> https://github.com/Chuanhsing/poe2-trade-zh/blob/main/js/translate.zh_TW.js
> 
> In Poe1, by using awakened-poe-trade + the English poe-trade webpage + the Poe1 version of this plugin(poe-trade-zh), I can perfectly search prices.



> @Kvan7 I found a GitHub repository for traditional Chinese localization of poe2-trade webpage, The translation files there might be helpful!
> 
> https://github.com/Chuanhsing/poe2-trade-zh/blob/main/js/translate.zh_TW.js
> 
> In Poe1, by using awakened-poe-trade + the English poe-trade webpage + the Poe1 version of this plugin(poe-trade-zh), I can perfectly search prices.



> @Kvan7 I found a GitHub repository for traditional Chinese localization of poe2-trade webpage, The translation files there might be helpful!
> 
> https://github.com/Chuanhsing/poe2-trade-zh/blob/main/js/translate.zh_TW.js
> 
> In Poe1, by using awakened-poe-trade + the English poe-trade webpage + the Poe1 version of this plugin(poe-trade-zh), I can perfectly search prices.
[translate.zh_TW.json](https://github.com/user-attachments/files/18184167/translate.zh_TW.json)
[translate.zh_TW.json](https://github.com/user-attachments/files/18184167/translate.zh_TW.json)
[translate.zh_TW.json](https://github.com/user-attachments/files/18184167/translate.zh_TW.json)
[translate.zh_TW.json](https://github.com/user-attachments/files/18184167/translate.zh_TW.json)

**Comment by Kvan7** [comment]
@KazumaIgarashi if you want to take a look at the [client strings](https://github.com/Kvan7/Exiled-Exchange-2/blob/master/renderer/public/data/en/client_strings.js) that the ui is using, that would  be a good place to start. At this point I am still working on getting it working for one other language, once that is done the others should take basically no time at all

**Comment by Kvan7** [comment]
Update:
![image](https://github.com/user-attachments/assets/2926d2bd-8377-4baa-9a57-a5b8cbd338b9)


Made some GOOOOOOD progress today :) :) :)

**Comment by Kvan7** [comment]
@yudka Yeah those are copied from the game's copy text so I don't think I can change them. I'll need to check(get feedback) if they are working right but they are used for `string.startswith(QUIVER__HELP_TEXT)`.

**Comment by Kvan7** [comment]
Currently localization is in a semi workable state. It basically just works for Russian but for Korean and Chinese it is giving my "not recognized" for about half of the modifiers. The remaining tasks I think I want to get done before shipping this are:
- Figure out and fix why half the mods aren't recognized
- Figure out and fix why the results always show up in english

**Comment by Kvan7** [comment]
<details>
<summary> I make NO promises and NO guarantees </summary>
(maybe released before the 25?)
</details>

**Comment by EasyBabi** [comment]
> Currently localization is in a semi workable state. It basically just works for Russian but for Korean and Chinese it is giving my "not recognized" for about half of the modifiers. The remaining tasks I think I want to get done before shipping this are:
> 
> * Figure out and fix why half the mods aren't recognized
> * Figure out and fix why the results always show up in english

@Kvan7 ready to work on that issue. Please assign

**Comment by Kvan7** [comment]
Will do, I'll write up those issues more when I have a bit of time. Right now I am hoping it's just a code issue somewhere but I'll have to see
