### ISSUE TITLE
Update Items/Stats for other languages

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#68]
Requires 2 parts, the game data tables, and trade api json files. 

- [x] Game data
- [x] Trade api json files

**Comment by Kvan7** [comment]
Getting errors  when trying to run `pathofexile-dat` with other languages. 
```
$ pathofexile-dat
Loading bundles index...
Loading schema for dat files
Exporting table "Data/BaseItemTypes"
Exporting table "Data/ItemClasses"
Exporting table "Data/WeaponTypes"
Exporting table "Data/ItemClassCategories"
Exporting table "Data/SkillGems"
Exporting table "Data/SkillGemInfo"
Exporting table "Data/Mods"
Exporting table "Data/Tags"
Exporting table "Data/UniqueStashLayout"
Exporting table "Data/Words"
Exporting table "Data/ItemVisualIdentity"
Exporting table "Data/Stats"
Exporting table "Data/Russian/BaseItemTypes"
Exporting table "Data/Russian/ItemClasses"
Exporting table "Data/Russian/WeaponTypes"
%APP_DATA%/npm/node_modules/pathofexile-dat/dist/bundles/index-bundle.js:69
        throw new Error('never');
              ^

Error: never
    at getFileInfo (%APP_DATA%/npm/node_modules/pathofexile-dat/dist/bundles/index-bundle.js:69:15)
    at FileLoader.getFileContents (%APP_DATA%/npm/node_modules/pathofexile-dat/dist/cli/bundle-loaders.js:31:26)
    at exportTables (%APP_DATA%/npm/node_modules/pathofexile-dat/dist/cli/export-tables.js:39:65)
    at async main (%APP_DATA%/npm/node_modules/pathofexile-dat/dist/cli/run.js:21:5)

Node.js v18.20.5
```

**Comment by Kvan7** [comment]
error is on
```
export function getFileInfo(path, bundlesInfo, filesInfo) {
    const hash = murmur64a(path.toLowerCase());
    const structOffset = findSequence(filesInfo, hash);
    if (structOffset === -1) {
        throw new Error('never');
    }
    const filesReader = new DataView(filesInfo.buffer, filesInfo.byteOffset, filesInfo.byteLength);
    const bundleIdx = filesReader.getInt32(structOffset + SFILE_HASH, true);
    const offsetInBundle = filesReader.getInt32(structOffset + SFILE_HASH + SFILE_BUNDLEIDX, true);
```

Which is implying broken data scheme

**Comment by maksim789456** [comment]
I saw it before the warning about some 5 files in ggpk cannot get path when use [LibGGPK3](https://github.com/aianlinb/LibGGPK3) lib early
![image](https://github.com/user-attachments/assets/a8f63c17-1075-48c5-b254-93f482258775)
It's maybe for some paths in "index" started used new hash algorithm or something else

I did quick patch `pathofexile-dat` lib to ignore files if not found struct offsets and it's start to works
![Code_IKZsyWzg1X](https://github.com/user-attachments/assets/e109a2f4-686d-4924-b8af-b3f1bd13f4f5)

**Comment by Kvan7** [comment]
I'll work on getting this in sometime this week. Probably won't touch today since I'm playing the game today

**Comment by Kvan7** [comment]
I did end up working on this a bit today, I got that patch applied @maksim789456 and that worked great, so thanks for the help with that!

Next things I need to get in terms of data is the json api stuff. I am pulling this data in [pull-json.sh](https://github.com/Kvan7/Exiled-Exchange-2/blob/dev/renderer/public/.DS_Store/pull-json.sh). 

This basically boils down to these endpoints:

- `en`
- [ ] https://www.pathofexile.com/api/trade2/data/filters
- [ ] https://www.pathofexile.com/api/trade2/data/items
- [ ] https://www.pathofexile.com/api/trade2/data/static
- [ ] https://www.pathofexile.com/api/trade2/data/stats


- `ru`
- [ ] https://ru.pathofexile.com/api/trade2/data/filters
- [ ] https://ru.pathofexile.com/api/trade2/data/items
- [ ] https://ru.pathofexile.com/api/trade2/data/static
- [ ] https://ru.pathofexile.com/api/trade2/data/stats


- `ko`
- [ ] https://poe.game.daum.net/api/trade2/data/filters
- [ ] https://poe.game.daum.net/api/trade2/data/items
- [ ] https://poe.game.daum.net/api/trade2/data/static
- [ ] https://poe.game.daum.net/api/trade2/data/stats


- `cmn-Hant`
- [ ] https://poe.game.qq.com/api/trade2/data/filters
- [ ] https://poe.game.qq.com/api/trade2/data/items
- [ ] https://poe.game.qq.com/api/trade2/data/static
- [ ] https://poe.game.qq.com/api/trade2/data/stats

These are all just json files that the trade site uses to function but contain item relationship information that helps to build out `items.ndjson` and `stats.ndjson` which are what the overlay uses to parse and things.

**Comment by Kvan7** [comment]
I am able access the `en` and `ru` api points, but I am not able to access the `ko` or `cmn-Hant` endpoints. Two options for this are A) somehow get these files to me so i can run the python script on them, or B) wait until the python script is working, then people who can access them can run the script to generate the ndjson files. 

Of the two I would probably prefer B, I'm still open to A, but with how frequently GGG is currently updating these files, almost nightly, I feel A would get to be complicated quite quickly. B would require more work since I need to get the DS_Store part of this into a much more stable state so that others can use it, and write a some documentation stuff relating to it.

**Comment by Kvan7** [comment]
For the first time just trying to get things working I would say that A will be much easier, but as a longer term solution I would say that I'm going to end up going with B.

**Comment by Kvan7** [comment]
@EasyBabi This would probably be something I'll reach out to you, probably email or github, to see if you are able to get these json files

**Comment by EasyBabi** [comment]
> @EasyBabi This would probably be something I'll reach out to you, probably email or github, to see if you are able to get these json files

I can pull the json files if you give me an instruction.

**Comment by vagrant-soul** [comment]
> 我今天确实做了一些工作，我应用了那个补丁@maksim789456效果非常好，非常感谢您的帮助！
> 
> 接下来我需要获取的数据是 json api 内容。我正在[pull-json.sh](https://github.com/Kvan7/Exiled-Exchange-2/blob/dev/renderer/public/.DS_Store/pull-json.sh)中提取这些数据。
> 
> 这基本上可以归结为以下端点：
> 
> * `en`
> * [x]  https://www.pathofexile.com/api/trade2/data/filters
> * [x]  https://www.pathofexile.com/api/trade2/data/items
> * [x]  https://www.pathofexile.com/api/trade2/data/static
> * [x]  https://www.pathofexile.com/api/trade2/data/stats
> * `ru`
> * [x]  https://ru.pathofexile.com/api/trade2/data/filters
> * [x]  https://ru.pathofexile.com/api/trade2/data/items
> * [x]  https://ru.pathofexile.com/api/trade2/data/static
> * [x]  https://ru.pathofexile.com/api/trade2/data/stats
> * `ko`
> * [ ]  https://poe.game.daum.net/api/trade2/data/filters
> * [ ]  https://poe.game.daum.net/api/trade2/data/items
> * [ ]  https://poe.game.daum.net/api/trade2/data/static
> * [ ]  https://poe.game.daum.net/api/trade2/data/stats
> * `cmn-Hant`
> * [ ]  https://poe.game.qq.com/api/trade2/data/filters
> * [ ]  https://poe.game.qq.com/api/trade2/data/items
> * [ ]  https://poe.game.qq.com/api/trade2/data/static
> * [ ]  https://poe.game.qq.com/api/trade2/data/stats
> 
> 这些都只是贸易网站用来运行的 json 文件，但包含有助于构建的项目关系信息`items.ndjson`，以及`stats.ndjson`覆盖层用来解析和事物的信息。
* :: `cmn-Hant'
At present, Tencent does not have a website related to poe2, these data you can get from another trading website 
https://pathofexile.tw/api/trade2/data/items
https://pathofexile.tw/api/trade2/data/stats
https://pathofexile.tw/api/trade2/data/static

**Comment by Kvan7** [comment]
I'm able to access those so that works!

**Comment by Kvan7** [comment]
@EasyBabi It looks like I can access `poe.game.daum.net` ones now for some reason? I am incredibly confused as to why it wasn't working 2 days ago but is now. I'm going to just download them myself then. Sorry for the confusion with this, and thank you for your help!

**Comment by Kvan7** [comment]
This is done now, just in bugfixing mode
