### ISSUE TITLE
Add/Remove client strings for other languages

### ISSUE THREAD

**Issue by Kvan7** [Kvan7/Exiled-Exchange-2#69]

**Comment by Kvan7** [comment]
This will require help. This task is basically going throught the `client_strings.js` and updating to implement the interface

**Comment by Kvan7** [comment]
right now i need translations for the requirements section. So when reading an item i need the starting part of the string in the requirements section. 
```
Item Class: Rings
Rarity: Rare
Morbid Whorl
Ruby Ring
--------
Requirements:
Level: 23
--------
Item Level: 39
--------
+27% to Fire Resistance (implicit)
--------
+33 to Accuracy Rating
+35 to Evasion Rating
+13% to Lightning Resistance
38% increased Mana Regeneration Rate
```
I need the first line from:
```
--------
Requirements:
Level: 23
--------
```
This allows me to know that it is the requirements section so that I do not pass it into the modifier parser

**Comment by AreChen** [comment]
In Chinese, this field should be translated as
REQUIREMENTS: '需求'

**Comment by Kvan7** [comment]
@EasyBabi I do have some string's I've added to `app_i18n.json` (just text used in the ui). If you have some time to translate them so they can be in Korean that would be great!

I do also need these in Russian, if someone is able to help to do that I would greatly appreciate it. 
```json
"poe2_new": {
    "beta_warning": "This is in BETA for POE2, things will not work always as expected.",
    "beta_warning2": "Please report any issues.",
    "pseudo_note": "Pseudo mods not supported by trade site",
    "pseudo_note2": "Items may appear to be more valuable than they actually are",
    "parse_error": "For some reason this item's stats did not parse.",
    "parse_error2": "It likely has a mod that is not supported yet.",
    "parse_error3": "(Potentially new or changed wording from poe1)",
    "bulk_exchange": "Bulk exchange rates are not implemented yet"
  }
```

**Comment by EasyBabi** [comment]
> @EasyBabi I do have some string's I've added to `app_i18n.json` (just text used in the ui). If you have some time to translate them so they can be in Korean that would be great!
> 
> I do also need these in Russian, if someone is able to help to do that I would greatly appreciate it.
> 
> ```json
> "poe2_new": {
>     "beta_warning": "This is in BETA for POE2, things will not work always as expected.",
>     "beta_warning2": "Please report any issues.",
>     "pseudo_note": "Pseudo mods not supported by trade site",
>     "pseudo_note2": "Items may appear to be more valuable than they actually are",
>     "parse_error": "For some reason this item's stats did not parse.",
>     "parse_error2": "It likely has a mod that is not supported yet.",
>     "parse_error3": "(Potentially new or changed wording from poe1)",
>     "bulk_exchange": "Bulk exchange rates are not implemented yet"
>   }
> ```

@Kvan7 you can find translated texts in the following. Please let me know if you need any other help. 

> ```json
> "poe2_new": {
>     "beta_warning": "이 버전은 베타버전입니다. 예기치 못한 버그가 있을 수 있습니다.",
>     "beta_warning2": "문제가 생기면 바로 알려주세요.",
>     "pseudo_note": "해당 접사는 아직 거래소에서 검색이 불가능 합니다.",
>     "pseudo_note2": "아이템이 원래의 가격보다 더 비쌀 수도 있습니다.",
>     "parse_error": "예기치 못한 문제로 이 아이템은 검색할 수 없습니다.",
>     "parse_error2": "아마 특정 접사가 아직 검색이 불가능한 것으로 보입니다.",
>     "parse_error3": "(새로운 접사 혹은 POE 1과 다르게 이름이 달라졌을 수도 있습니다)",
>     "bulk_exchange": "아이템 대량교환 비율 표시는 아직 시행되지 않습니다."
>   }
> ```

**Comment by Kvan7** [comment]
Awesome, thank you so much for your help! If you are open to help in the future I'll be sure to reach out

**Comment by EasyBabi** [comment]
> Awesome, thank you so much for your help! I'll be sure to reach out if I need more help!
 
Anytime. I will love to help. Do you know when I can expect to see this working in ko?

**Comment by EasyBabi** [comment]
> Not 100% sure. At this point in time it _seems_ largely dependent on #67. Basically once I can get from game data files to have `items.ndjson` and `stats.ndjson` files it should be done. I'm not the greatest at estimating these things, but I would say maybe a week?

Sounds like a plan. You can always ask any help for 'ko' related stuff. Thanks for your hard work!

**Comment by vagrant-soul** [comment]
> 现在我需要需求部分的翻译。因此，在阅读项目时，我需要需求部分中字符串的起始部分。
> 
> ```
> Item Class: Rings
> Rarity: Rare
> Morbid Whorl
> Ruby Ring
> --------
> Requirements:
> Level: 23
> --------
> Item Level: 39
> --------
> +27% to Fire Resistance (implicit)
> --------
> +33 to Accuracy Rating
> +35 to Evasion Rating
> +13% to Lightning Resistance
> 38% increased Mana Regeneration Rate
> ```
> 
> 我需要以下第一行：
> 
> ```
> --------
> Requirements:
> Level: 23
> --------
> ```
> 
> 这让我知道它是需求部分，这样我就不会将它传递到修饰符解析器中

物品種類: 弓
稀有度: 稀有
亂世 之弦
專家狂熱者之弓
--------
品質: +20% (augmented)
物理傷害: 267-460 (augmented)
暴擊率: 6.21% (augmented)
每秒攻擊次數: 1.30 (augmented)
--------
需求:
等級: 77
敏捷: 212 (unmet)
--------
插槽: S S 
--------
物品等級: 80
--------
增加 40% 物理傷害 (rune)
--------
增加 142% 物理傷害
附加 23 至 52 物理傷害
+65 命中值
+1.21% 暴擊率
增加 8% 攻擊速度
每個被擊殺的敵人，獲得 42 生命

**Comment by vagrant-soul** [comment]
> 现在我需要需求部分的翻译。因此，在阅读项目时，我需要需求部分中字符串的起始部分。
> 
> ```
> Item Class: Rings
> Rarity: Rare
> Morbid Whorl
> Ruby Ring
> --------
> Requirements:
> Level: 23
> --------
> Item Level: 39
> --------
> +27% to Fire Resistance (implicit)
> --------
> +33 to Accuracy Rating
> +35 to Evasion Rating
> +13% to Lightning Resistance
> 38% increased Mana Regeneration Rate
> ```
> 
> 我需要以下第一行：
> 
> ```
> --------
> Requirements:
> Level: 23
> --------
> ```
> 
> 这让我知道它是需求部分，这样我就不会将它传递到修饰符解析器中

 > ```
>物品種類: 弓
>稀有度: 稀有
>亂世 之弦
>專家狂熱者之弓
>--------
>品質: +20% (augmented)
>物理傷害: 267-460 (augmented)
>暴擊率: 6.21% (augmented)
>每秒攻擊次數: 1.30 (augmented)
>--------
>需求:
>等級: 77
>敏捷: 212 (unmet)
>--------
>插槽: S S 
>--------
>物品等級: 80
>--------
>增加 40% 物理傷害 (rune)
>--------
>增加 142% 物理傷害
>附加 23 至 52 物理傷害
>+65 命中值
>+1.21% 暴擊率
>增加 8% 攻擊速度
>每個被擊殺的敵人，獲得 42 生命
> ```

**Comment by Kvan7** [comment]
I do apologize @vagrant-soul, I'm not quite sure what you are asking? This is referencing the comment above it seems, so would guess this is providing the copy-text of an item in the game, but in Chinese for the purpose of doing the localizations?

**Comment by vagrant-soul** [comment]
Yes, I see you need some translations for the requirements section, Chinese for the purpose of localisation.

**Comment by Kvan7** [comment]
Awesome! Thank you for providing this!

**Comment by Kvan7** [comment]
@EasyBabi For your timing, the python script update is not moving along as fast as I would hope, so at this point it will probably be longer than a week now. Kinda trying to split my time between getting updates to main, localization and playing the game. 
For the holidays everything in general will probably slow down a decent bit, I will be on a laptop not my normal computer so I'll have to re-setup stuff soon too. 
Sorry for having to push it back a bit

**Comment by yudka** [comment]
> @EasyBabi
> I do also need these in Russian, if someone is able to help to do that I would greatly appreciate it.
> 
> ```json
> "poe2_new": {
>     "beta_warning": "This is in BETA for POE2, things will not work always as expected.",
>     "beta_warning2": "Please report any issues.",
>     "pseudo_note": "Pseudo mods not supported by trade site",
>     "pseudo_note2": "Items may appear to be more valuable than they actually are",
>     "parse_error": "For some reason this item's stats did not parse.",
>     "parse_error2": "It likely has a mod that is not supported yet.",
>     "parse_error3": "(Potentially new or changed wording from poe1)",
>     "bulk_exchange": "Bulk exchange rates are not implemented yet"
>   }
> ```

In Russian 

```
"poe2_new": {
    "beta_warning": "Функционал для PoE2 находится в стадии бета тестирования и не всегда работает так, как задумано.",
    "beta_warning2": "Пожалуйста сообщайте о возникающих ошибках.",
    "pseudo_note": "Псевдо модификаторы не поддерживаются торговым сайтом",
    "pseudo_note2": "Предметы могут отображаться более ценными, чем они являются",
    "parse_error": "По какой то причине модификаторы предмета не прошли парсинг.",
    "parse_error2": "Скорее всего у предмета имеется пока не поддерживаемое свойство.",
    "parse_error3": "(Возможно новое или отличное от PoE1 по написанию)",
    "bulk_exchange": "Соотношения для оптовых продаж пока не внедрены"
  }
```

**Comment by EasyBabi** [comment]
> @EasyBabi For your timing, the python script update is not moving along as fast as I would hope, so at this point it will probably be longer than a week now. Kinda trying to split my time between getting updates to main, localization and playing the game. For the holidays everything in general will probably slow down a decent bit, I will be on a laptop not my normal computer so I'll have to re-setup stuff soon too. Sorry for having to push it back a bit

 All good. I would rather have it seamless than one with errors. Please take your time and let me know if there is anything I can help. Tbh, game is too good not to play (I feel you). Merry Christmas and Happy Holiday!

**Comment by yudka** [comment]
> right now i need translations for the requirements section. So when reading an item i need the starting part of the string in the requirements section.

According to text ive got in Russian game version with exiled exchange 

```
Класс предмета: Кольца
Редкость: Редкий
Болезненный Завиток
Кольцо с рубином
--------
Требования:
Уровень: 23
--------
Уровень предмета: 39
--------
+27% к сопротивлению огню (implicit)
--------
+33 к меткости
+35 к уклонению
+13% к сопротивлению молнии
38% повышение скорости регенерации маны
```

I dont know why all stats are lower cased but if you need them in upper case like in your text fragment:

```
+27% к Сопротивлению Огню (implicit)
--------
+33 к Меткости
+35 к Уклонению
+13% к Сопротивлению Молнии
38% повышение Скорости Регенерации Маны
```

Also since PoE naming is some times kind of a joke in Russian i am not 100% shure about naming translation.

**Comment by Kvan7** [comment]
More or less done, anything remaining will be opened individually as bugs/errors
