### ISSUE TITLE
Linux AppImage

### ISSUE THREAD

**Issue by JoshIce** [Kvan7/Exiled-Exchange-2#72]
I've just finished building the AppImage for Linux on my system and it seems to be working great!

It would be really nice if we could get the AppImage uploaded in each release.

**Comment by Kvan7** [comment]
I'll add it back into the gh actions for next release, it was causing the builds to fail previously, but i'll see if it's working for next release

**Comment by jeagerx** [comment]
> I've just finished building the AppImage for Linux on my system and it seems to be working great!
> 
> It would be really nice if we could get the AppImage uploaded in each release.

how do you build it ?

**Comment by Kvan7** [comment]
see [developing.md](https://github.com/Kvan7/Exiled-Exchange-2/blob/master/DEVELOPING.md)

**Comment by JoshIce** [comment]
> how do you build it ?

I actually ended up having to follow the github action directly and modify them slightly. I'll post the process here in case anyone else gets stuck. Fair warning, if you don't have an environment setup to run these commands I wouldn't recommend trying to build this now. Wait until the github pipeline is working hopefully in the next release.

Instructions are as follows:

```
cd renderer
npm ci
npm run make-index-files
npm run build

cd ../main
npm ci
npm run build
npm run package
```
The file should now exist at main/dist/Exiled Exchange 2-0.1.0.AppImage

**Comment by enpinzolas** [comment]
I did a small script that updates the repo and regenerates the old AppImage, replacing the old one (this is useful because things like KRunner or any desktop link will work post update even if the version changes. It's basically the same commands as @JoshIce :

```bash
#!/bin/bash

dir=$(dirname $0)
final_path=~/utils/poe/exiled-exchange-2.AppImage
cd $dir
git pull

echo "***************************************"
echo "*****  Running the renderer build  ****"
echo "***************************************"

cd renderer
npm ci &> '/dev/null'
npm run make-index-files
npm run build

echo "***************************************"
echo "*****    Running the main build    ****"
echo "***************************************"

cd ../main
npm ci
npm run build

echo "***************************************"
echo "*****   Running the main package   ****"
echo "***************************************"

npm run package
for file in dist/Exiled*AppImage
do
  mv $file $final_path
done

echo "AppImage moved to  $final_path. Enjoy!"
echo "***************************************"
echo "*****   Update Finished! ( ͡° ͜ʖ ͡°)  ****"
echo "***************************************"

```

It basically works, then I can launch the program via krunner writting exiledex and pressing enter and voila.

**Comment by jeagerx** [comment]
I was able to build it yesterday but didnt know where it will land :D thanks
However this have the same issues that I had on Awakener, new window open on second screen and disappear if I try to click it (i'm on KDE & Wayland)

**Comment by Ihnivid** [comment]
> However this have the same issues that I had on Awakener, new window open on second screen and disappear if I try to click it (i'm on KDE & Wayland)

Obviously a "bad" workaround, but I've had similar issues on Wayland, switched back to X and Awakened ran fine.

**Comment by thevinter** [comment]
The application seems to be working (trade is down so can't confirm), but I'm getting the following error at launch:
```
Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/Kvan7/exiled-exchange-2/releases/download/v0.1.0/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/Kvan7/exiled-exchange-2/releases/download/v0.1.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
```

FYI if you have a tiling manager you'll need to open the app in floating mode and make sure to have a compositor enabled/installed (some `gamemode` configurations close compositors on game launch)

**Comment by Jookia** [comment]
For anyone with Mint and/or Distrobox installed, you can create a build environment and enter it like this:

```
sudo apt install distrobox
distrobox create --image ubuntu:latest --name exile-build && distrobox enter exile-build
```

Then build it by doing  this:

```
sudo apt -y install git npm
git clone https://github.com/Kvan7/Exiled-Exchange-2/
cd Exiled-Exchange-2
cd renderer
npm ci
npm run make-index-files
npm run build
cd ../main
npm ci
npm run build
npm run package
```

The output AppImage is in ```~/Exiled-Exchange-2/main/dist```

**Comment by jeagerx** [comment]
> > However this have the same issues that I had on Awakener, new window open on second screen and disappear if I try to click it (i'm on KDE & Wayland)
> 
> @jeagerx Obviously a "bad" workaround, but I've had similar issues on Wayland, switched back to X and Awakened ran fine. Not sure if that's an option for you.

Yeah i guess that was just with wayland but i will not switch just for that :(
I'm willing to help but not sure if @Kvan7 will spend time on this

**Comment by Kvan7** [comment]
AppImage will be in today's release hopefully

**Comment by hparadiz** [comment]
The main hot key Shift + Space works for you guys on Linux? I had to change it to Shift + N
