### ISSUE TITLE
[Not Recognized Modifier] - Charm Slots: 1

### ISSUE THREAD

**Issue by chewbacca2314** [Kvan7/Exiled-Exchange-2#75]
## Parse Error
Item Class: Belts 
`Charm Slots: 1`

### Item Text
Charm Slots parsing as not recognized modifier
- Can be copied with `ctrl`+`shift`+`c`
- Can also be copied from below the error message

```
Item Class: Belts
Rarity: Rare
Gale Trap
Mail Belt
--------
Charm Slots: 1
--------
Requirements:
Level: 56
--------
Item Level: 80
--------
11% reduced Flask Charges used (implicit)
--------
+29 to Armour
+136 to maximum Mana
+76 to Stun Threshold
33% increased Flask Charges gained
27 to 38 Physical Thorns damage


```

**Comment by Kvan7** [comment]
Yep problem with all belts, i should just need to add a short parser for it. Not going to worry about right now since all belts are 1 as far as I have heard

**Comment by tyrielgrand** [comment]
to be a belt with 2 or 3 charm spots they need the modifier "# Charm Slot"  i linked to a search that have the modifier [https://www.pathofexile.com/trade2/search/poe2/Standard/GWXRLjosb](https://www.pathofexile.com/trade2/search/poe2/Standard/GWXRLjosb)

**Comment by Kvan7** [comment]
what they exist? Alrightly then, I'll try and get a parser with this in it up and going soon

**Comment by Kvan7** [comment]
based on how this is implemented in trade api, i need an item's copy text with the +charm slots stat. min value of 1 gives 2 charms so for this section in a belt I will just ignore
