### ISSUE TITLE
[Not Recognized Modifier] - #% increased Physical Damage

### ISSUE THREAD

**Issue by decimetras** [Kvan7/Exiled-Exchange-2#82]
### Description
Error: Unknown stat provided: explicit.stat_419810844

### Reproduction steps
check price of a weapon with inc phys mod, select inc phys

### Screenshot
![image](https://github.com/user-attachments/assets/bde287be-b1a7-45c7-a2c0-744e88cf2651)

**Comment by Kvan7** [comment]
What version are you running? And can you please provide the copy text of this item so that I can test it and potential fixes
Copy item with ctrl+c while hovering over it and paste inside of three backticks so that it is formatted correctly (  ` )
ex:
```
Item Class: Rings
Rarity: Rare
Morbid Whorl
Ruby Ring
--------
Requirements:
Level: 23
--------
Item Level: 39
--------
+27% to Fire Resistance (implicit)
--------
+33 to Accuracy Rating
+35 to Evasion Rating
+13% to Lightning Resistance
38% increased Mana Regeneration Rate
```

**Comment by decimetras** [comment]
using 0.1.0

```Item Class: Two Hand Maces
Rarity: Rare
Chimeric Crack
Expert Forge Maul
--------
Quality: +20% (augmented)
Physical Damage: 415-573 (augmented)
Critical Hit Chance: 5.00%
Attacks per Second: 1.05
--------
Requirements:
Level: 67
Str: 174
--------
Sockets: S S 
--------
Item Level: 82
--------
40% increased Physical Damage (rune)
--------
75% increased Physical Damage
Adds 49 to 71 Physical Damage
127% increased Elemental Damage with Attacks
Grants 4 Life per Enemy Hit
Gain 17 Mana per Enemy Killed
16% increased Stun Duration
```
but now it shows this, probably because of server maintenance currently going
![image](https://github.com/user-attachments/assets/3fdc45d7-2d6b-441e-a714-b080de69b63b)

**Comment by Kvan7** [comment]
yeah cloudflare ddos protection is enabled rn, you can hit browser to open in browser but not a hole lot able to do about the ddos protection part, sorry.

**Comment by Kvan7** [comment]
Seems to potentially be due to basetype not being recognized as a weapon

**Comment by Garrett-Preston** [comment]
![image](https://github.com/user-attachments/assets/290dfd0d-712e-4177-b18b-f15a86869837)

Item Class: One Hand Maces
Rarity: Rare
Fate Batter
Advanced Warpick
--------
Physical Damage: 68-92 (augmented)
Critical Hit Chance: 8.00%
Attacks per Second: 1.71 (augmented)
--------
Requirements:
Level: 58
Str: 117 (unmet)
--------
Item Level: 73
--------
+34% to Critical Damage Bonus (implicit)
--------
100% increased Physical Damage
+53 to Accuracy Rating
+39% to Critical Damage Bonus
18% increased Attack Speed

I am having problems with the same mod. It doesn't show it here but it likely has something to do with it being hybrid. T3 increased phys and T3 hybrid %phys/accuracy

**Comment by Kvan7** [comment]
This is completed, will be in next release
