### ISSUE TITLE
Game invisible: overlay blocks entire screen (grayed out)

### ISSUE THREAD

**Issue by bartkleinreesink** [Kvan7/Exiled-Exchange-2#84]
### Description
Please see the video. When I start the program, it says it's loaded, but the overlay on the games window is solid and will only dissapear when not focusing on the game window. This happens in windowed, fullscreen and windowed fullscreen. Disabling Discord has no effect. Switching from Vulkan to DirectX12 has no effect.

### Video
https://github.com/user-attachments/assets/741cceca-eff1-4788-bd6f-865f1e4247c7

### Reproduction steps
Probably machine specific, but just launch the program and open the POE2 window.

### Screenshot
Graphics:
![image](https://github.com/user-attachments/assets/d4cf9c01-9f79-491d-b935-bc099bce36b4)
![image](https://github.com/user-attachments/assets/b1874c4b-b709-460d-a689-b017e2f4549b)
![image](https://github.com/user-attachments/assets/e5850528-360f-49c0-a12b-f9227cf89358)

### msinfo32 (shortened)
| **Property**                                         | **Value**                                                                                     |
|-----------------------------------------------------|---------------------------------------------------------------------------------------------|
| **Operating System Name**                           | Microsoft Windows 11 Pro                                                                    |
| **Version**                                         | 10.0.26100 Build 26100                                                                      |
| **Operating System Vendor**                         | Microsoft Corporation                                                                       |
| **System Manufacturer**                             | Gigabyte Technology Co., Ltd.                                                              |
| **System Model**                                     | B450 AORUS PRO                                                                              |
| **System Type**                                      | x64-based PC                                                                               |
| **Graphics card** | AMD Radeon RX 5700 XT |
| **Processor**                                       | AMD Ryzen 5 3600 6-Core Processor, 3593 MHz, 6 cores, 12 logical processors                |
| **BIOS Version/Date**                               | American Megatrends Inc. F50, 27/11/19                                                     |
| **SMBIOS Version**                                  | 3.2                                                                                        |
| **Embedded Controller Version**                     | 255.255                                                                                    |
| **BIOS Mode**                                       | UEFI                                                                                       |
| **Baseboard Manufacturer**                          | Gigabyte Technology Co., Ltd.                                                              |
| **Baseboard Product**                               | B450 AORUS PRO-CF                                                                          |
| **Secure Boot State**                               | Disabled                                                                                   |
| **PCR7 Configuration**                              | Permission needed to view                                                                  |
| **Boot Device**                                     | \Device\HarddiskVolume5                                                                    |
| **Locale**                                          | United States                                                                              |
| **HAL (Hardware Abstraction Layer)**                | Version = "10.0.26100.1"                                                                   |
| **Time Zone**                                       | Western Europe Standard Time                                                              |
| **Installed Physical Memory (RAM)**                 | 32.0 GB                                                                                   |
| **Total Physical Memory**                           | 31.9 GB                                                                                   |
| **Available Physical Memory**                       | 14.0 GB                                                                                   |
| **Total Virtual Memory**                            | 33.9 GB                                                                                   |
| **Available Virtual Memory**                        | 7.64 GB                                                                                   |
| **Page File Space**                                 | 2.00 GB                                                                                   |
| **Page File**                                       | C:\pagefile.sys                                                                            |
| **Kernel DMA Protection**                           | Disabled                                                                                   |
| **Virtualization-Based Security**                   | Running                                                                                    |

**Comment by Kvan7** [comment]
Can you see what the setting is for General>"Background when the Overlay is clickable"? This may be related to a general bug listed from original awakened relating to "mica for everyone" i think. something with backdrop type not being set to default

**Comment by bartkleinreesink** [comment]
I will check asap, you might be right because I have Mica for Everyone installed. Was already wondering if that was the culprit.

**Comment by bartkleinreesink** [comment]
Closing Mica for Everyone and restarting Exiled Exchange 2 solved the problem.
