### ISSUE TITLE
[Parse Error] - % based value not updating

### ISSUE THREAD

**Issue by Koxomathical** [Kvan7/Exiled-Exchange-2#88]
During price check the mod value autofills the exact value on the item regardless of settings for me

![Screenshot 2024-12-17 19 26 17](https://github.com/user-attachments/assets/ce0e6a39-18be-46e2-97e1-432c74c88568)

**Comment by Kvan7** [comment]
Feel free to un notify, I am going to be using this to document where I am checking stuff just so I can reference in the future

**Comment by Kvan7** [comment]
Is correctly reading setting from file: yes
calls `initUiModFilters`

**Comment by Kvan7** [comment]
This does call to correct method and generates a good range?

**Comment by Kvan7** [comment]
Ah, it's using `filterBounds` always instead of `filterDefault` for some reason.

**Comment by Kvan7** [comment]
This smells like upstream. If it is i think i can do a patch to fix  but it will probably be very ugly patch

**Comment by Kvan7** [comment]
Yep upstream. looks like the fix is somewhat easy but idk how hacky it is. 

Ended up being missing advanced item descriptions/cant copy them so the blocking issue is #64

**Comment by Kvan7** [comment]
Fix seems to work. It is bypassing a min/max check so that could lead to bugs. This does break "perfect" rolls though so users will have to manually set when a perfect roll occers
