### ISSUE TITLE
Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by MeyoD** [Kvan7/Exiled-Exchange-2#89]
when searching for items with ctrl  +d this happens Error: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

**Comment by kaelken** [comment]
Getting the same error as well.

**Comment by ArifOzan** [comment]
yeah same

**Comment by N1ckola5** [comment]
Also getting this error

**Comment by J1Farkus** [comment]
+1

**Comment by Kendricon** [comment]
Same +1

**Comment by ComMcNeil** [comment]
its a general API issue by GGG, they changed the API - the app "Sidekick" has the same problems.

**Comment by ASMRguy** [comment]
So it is current thing, that happens right now, as we type it.

**Comment by mouadelmou** [comment]
same here

**Comment by robciog** [comment]
working workaround is to click Trade button to open trade site with filled search parameters

**Comment by XcentriXTV** [comment]
Same +1

**Comment by Kvan7** [comment]
GGG has enabled a stricter version of cloudflare's protection on the trade site. This program gets filtered out since it is indecipherable from a bot. 
Click the browser button to pull up the trade in either default browser or in game browser to have all the listed filters pre-filled out

**Comment by Kvan7** [comment]
locking cause i don't need more pings for this. please react to the top level with thumbs up instead of "+1" comments. Thank you!

**Comment by Kvan7** [comment]
The cloudflare protection is back to normal so this should be fully working again. I'll probably add a way for the program to tell when it is this error but that will be much later in the future
