### ISSUE TITLE
Open in Browser opens in app

### ISSUE THREAD

**Issue by s-mabdurrazak** [Kvan7/Exiled-Exchange-2#99]
### Description
Previously with Awakened, clicking on "Browser" would open a new tab with the item name and affixes filled out in the trade. This no longer happens with Exile-Exchange. Instead, the trade store opens "in-app". It covers the fullscreen monitor that the game is on and is obstrusive

### Reproduction steps
Ctrl + Alt + D
Click on Browser to open it up

### Screenshot
![image](https://github.com/user-attachments/assets/6c545b21-b73f-49bc-b2e3-658ad06e56eb)

![image](https://github.com/user-attachments/assets/440800d2-0d23-43c1-82e2-e39d00a01b06)

Note the second image is not in an actual browser. It will disappear if I close the modal.

**Comment by rauldzmartin** [comment]
You should disable "builtin browser" in the app price check settings.

![price check](https://github.com/user-attachments/assets/de446565-57ba-4549-8c20-56d113ec7a18)
